-- 실콘텐츠 채우기: 음식 31~50번 (대표 K푸드 20종) — 2026-07-07, 솔
-- 기존 30종에 없는 전국구 대표 음식을 추가해 50종 목표를 채운다.
-- display_order는 기존 최대값(300) 다음인 310부터 10 간격.
-- 재실행해도 안전하도록 on conflict (slug) do nothing 사용.
-- 되돌리기: delete from public.foods where slug in (아래 slug 목록);

insert into public.foods
  (slug, name_en, name_ko, description, taste_profile, spicy_level, beginner_note, display_order, status)
values
  ('bibimbap', 'Bibimbap', '비빔밥',
   'Rice bowl topped with seasoned vegetables, egg, and gochujang you mix yourself.',
   'savory, balanced, customizable', 1,
   'Mix everything before eating; add gochujang little by little to control the heat.',
   310, 'published'),
  ('bulgogi', 'Bulgogi', '불고기',
   'Thin-sliced beef marinated in a sweet soy sauce and grilled or pan-cooked.',
   'sweet, savory, tender', 0,
   'One of the safest first orders in Korea — sweet, mild, and easy to share.',
   320, 'published'),
  ('kimchi-jjigae', 'Kimchi Jjigae', '김치찌개',
   'Bubbling stew of aged kimchi, pork or tuna, and tofu served with rice.',
   'spicy, sour, deep', 3,
   'Comes boiling hot — let it cool and eat it spoon-by-spoon over rice.',
   330, 'published'),
  ('sundubu-jjigae', 'Sundubu Jjigae', '순두부찌개',
   'Soft tofu stew in a spicy broth, usually served with a raw egg to crack in.',
   'spicy, silky, warming', 2,
   'Ask for mild (soon-han-mat) if you want the silky tofu without the burn.',
   340, 'published'),
  ('doenjang-jjigae', 'Doenjang Jjigae', '된장찌개',
   'Everyday soybean-paste stew with tofu and vegetables, deeper than miso.',
   'savory, earthy, homey', 1,
   'This is Korean home cooking — order it with any grilled meat meal.',
   350, 'published'),
  ('samgyeopsal', 'Samgyeopsal', '삼겹살',
   'Thick pork belly grilled at the table and wrapped in lettuce with ssamjang.',
   'rich, smoky, hands-on', 0,
   'Wrap a piece in lettuce with garlic and ssamjang — one bite per wrap.',
   360, 'published'),
  ('gimbap', 'Gimbap', '김밥',
   'Seaweed rice rolls filled with vegetables, egg, and ham — Korea''s picnic food.',
   'mild, fresh, portable', 0,
   'A cheap, filling grab-and-go option; perfect for day trips and trains.',
   370, 'published'),
  ('japchae', 'Japchae', '잡채',
   'Glass noodles stir-fried with vegetables and beef in a sweet soy seasoning.',
   'sweet, savory, chewy', 0,
   'Mild and slightly sweet — a reliable choice for cautious eaters.',
   380, 'published'),
  ('haemul-pajeon', 'Haemul Pajeon', '해물파전',
   'Crispy scallion pancake loaded with seafood, torn and shared at the table.',
   'crispy, savory, briny', 0,
   'Traditionally paired with makgeolli (rice wine), especially on rainy days.',
   390, 'published'),
  ('dak-galbi', 'Dak Galbi', '닭갈비',
   'Spicy stir-fried chicken with cabbage and rice cakes cooked on a big pan.',
   'spicy, sweet, sizzling', 2,
   'Add fried rice (bokkeumbap) to the leftover sauce at the end — locals always do.',
   400, 'published'),
  ('jjimdak', 'Jjimdak', '찜닭',
   'Braised chicken with glass noodles and vegetables in a soy-based sauce.',
   'savory, sweet, garlicky', 2,
   'Portions are large and made for sharing; ask for less spicy if needed.',
   410, 'published'),
  ('gamjatang', 'Gamjatang', '감자탕',
   'Hearty pork backbone stew with potatoes and perilla — a late-night favorite.',
   'spicy, meaty, rustic', 2,
   'Eating the meat off the bone is normal here — plastic gloves are often provided.',
   420, 'published'),
  ('eomuk', 'Eomuk Skewers', '어묵',
   'Fish cake skewers simmered in warm broth, sold at street stalls everywhere.',
   'mild, warm, comforting', 0,
   'The broth is free at most stalls — drink it from the paper cup provided.',
   430, 'published'),
  ('gyeranppang', 'Gyeranppang', '계란빵',
   'Warm street-food bread with a whole egg baked on top — a winter classic.',
   'sweet, eggy, fluffy', 0,
   'Best eaten hot off the cart; watch out for the steam on the first bite.',
   440, 'published'),
  ('sundae', 'Sundae', '순대',
   'Korean blood sausage stuffed with glass noodles, served with salt for dipping.',
   'savory, chewy, adventurous', 1,
   'An adventurous pick — start with one piece dipped in the seasoned salt.',
   450, 'published'),
  ('ramyeon', 'Ramyeon', '라면',
   'Instant noodles elevated to a food culture — cooked to order at snack bars.',
   'spicy, savory, nostalgic', 2,
   'Try it at a convenience store counter with a cheese slice or egg added.',
   460, 'published'),
  ('bingsu', 'Bingsu', '빙수',
   'Shaved-ice dessert piled with sweet red bean, fruit, or injeolmi rice cake.',
   'sweet, icy, shareable', 0,
   'One bowl is usually enough for two people — it melts fast, so dig in.',
   470, 'published'),
  ('tteokgalbi', 'Tteokgalbi', '떡갈비',
   'Grilled short-rib patties — juicy, slightly sweet, and easy to eat.',
   'savory, sweet, juicy', 1,
   'Think of it as Korea''s premium burger patty; no bones, no fuss.',
   480, 'published'),
  ('yukhoe', 'Yukhoe', '육회',
   'Korean beef tartare with pear and egg yolk, a Gwangjang Market specialty.',
   'savory, silky, fresh', 0,
   'Served raw — order it at busy specialist stalls where turnover is high.',
   490, 'published'),
  ('kimchi-bokkeumbap', 'Kimchi Bokkeumbap', '김치볶음밥',
   'Fried rice made with kimchi and topped with a fried egg — simple and addictive.',
   'spicy, tangy, satisfying', 2,
   'A safe way to try kimchi flavor in a familiar fried-rice format.',
   500, 'published')
on conflict (slug) do nothing;

-- 지역 연결 (region_foods) — 이미 있는 지역 slug에만 연결
insert into public.region_foods (region_id, food_id, display_order)
select r.id, f.id, v.display_order
from (values
  ('jongno',           'bibimbap',          10),
  ('seoul',            'bibimbap',          20),
  ('seoul',            'bulgogi',           30),
  ('gangnam',          'bulgogi',           40),
  ('jongno',           'kimchi-jjigae',     50),
  ('seoul',            'kimchi-jjigae',     60),
  ('seoul',            'sundubu-jjigae',    70),
  ('jongno',           'doenjang-jjigae',   80),
  ('mapo',             'samgyeopsal',       90),
  ('seoul',            'samgyeopsal',      100),
  ('seoul',            'gimbap',           110),
  ('myeongdong',       'gimbap',           120),
  ('seoul',            'japchae',          130),
  ('gwangjang-market', 'haemul-pajeon',    140),
  ('jongno',           'haemul-pajeon',    150),
  ('hongdae',          'dak-galbi',        160),
  ('hongdae',          'jjimdak',          170),
  ('dongdaemun',       'gamjatang',        180),
  ('myeongdong',       'eomuk',            190),
  ('myeongdong',       'gyeranppang',      200),
  ('gwangjang-market', 'sundae',           210),
  ('sindang',          'sundae',           220),
  ('seoul',            'ramyeon',          230),
  ('gangnam',          'bingsu',           240),
  ('suwon',            'tteokgalbi',       250),
  ('gwangjang-market', 'yukhoe',           260),
  ('seoul',            'kimchi-bokkeumbap', 270)
) as v(region_slug, food_slug, display_order)
join public.regions r on r.slug = v.region_slug
join public.foods f on f.slug = v.food_slug
on conflict (region_id, food_id) do nothing;
